title: Xiaokang Wang - Mathematics
description: Academic homepage
baseurl: ""
url: "https://Mathheadkang.github.io"
markdown: kramdown
theme: minima

kramdown:
  math_engine: null

# Navigation menu
header_pages:
  - index.md
  - research/index.md
  - projects/index.md
  - teaching/index.md
  - cv/index.md